junit:
    stage: test
    script:
        - cd FittnessTrackerApp mvn -B clean test
generate_artifacts:
    stage: deploy
    script:
        - cd FittnessTrackerApp mvn -B clean package
    artifacts:
        paths:
            - FittnessTrackerApp/target/Fittness*.jar
