junit:
    stage: test
    script:
        - cd Fitness-Tracker-App
        - mvn -B clean test
generate_artifacts:
    stage: deploy
    script:
        - cd Fitness-Tracker-App
        - mvn -B clean package
    artifacts:
        paths:
            - Fitness-Tracker-App/target/Fitness*.jar
